### ISSUE TITLE
As a Catalogue of Life user I want a return of different ID

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnlist-resolver-gui#34]
The tax_id field that the resolver imports from CoL and outputs in the results is useless, it is just a database index id, changes with every edition and is not used in other CoL services. Unfortunately CoL is in a transition phase from offering LSIDs earlier to 'natural keys' after AC2017 edition. These are however already in DwC, in the references field. I would suggest to extract these from the references field. Example: from http://www.catalogueoflife.org/annual-checklist/details/species/id/1d761fa6e15f9ba277ad7784af78c8b4/synonym/5fc5c8ab89caeede5ede03be346369a7 the identifier can be extracted for both the synonym and its current accepted name. It may also be helpful to give this whole url in the output.

**Comment by dimus** [comment]
Suggestions for the future CoL DwCA according to discoveries during import:

* There are two lines with non-UTF-8 characters in vernalcuar names file. It is good to check for these. Here is an example in Ruby how to detect them:

```
#!/usr/bin/env ruby

def check_utf(f)
  open(f, 'r:utf-8').each_with_index do |l, i|
    puts format('File: %s, Line%s\nl\n\n', f, i) unless l.valid_encoding?
  end
end

Dir.entries('.').select { |f| f =~ /\.txt$/ }.each do |f|
  check_utf(f)
end
```

* <feff> (Unicode Character 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF)) happens in the files, would be good to remove all BOM characters from DwCA

* Change IDs in DwCA according to this ticket (it would also require to introduce these IDs for ~170k records that do not have them -- looks like all of them are genera). Example:

```
33781733,urn:lsid:catalogueoflife.org:taxon:0aa9be85-d35f-11e6-9d3f-bc764e092680:col20170308,Species 2000,Catalogue
 of Life in Species 2000 & ITIS Catalogue of Life: 22nd March 2017,,33527721,,genus,,Paedovaricus,Animalia,Chordata
,Actinopterygii,Perciformes,,Gobiidae,Paedovaricus,Paedovaricus,,,,,,,,,,,,,false
```


They are the all located in the end of the taxa.txt file. It would be great if they could have ID's that are more consistent with new stable IDs

* There are quite a few `&amp;` instead of `&` Mostly coming from `World Ferns` looks like

**Comment by ruud-altenburg** [comment]
Believe me, I have tried for hours and hours to remove invalid utf8 characters. It's one thing to detect them, it's another thing to convert or to strip them properly. In the original database these are html entities!

Best thing is to report offending records to Yuri/Luisa.

**Comment by ruud-altenburg** [comment]
Genera are no valid endpoints in the CoL, so they don't need to have a natural key.

**Comment by ruud-altenburg** [comment]
As of a few days ago, http://www.catalogueoflife.org/DCA_Export/ serves natural keys instead of LSIDs.

**Comment by dimus** [comment]
@ruud-altenburg One more thing --- url is missing /2017. It should be
http://www.catalogueoflife.org/annual-checklist/2017/details/species/id/b480a8154e43e27addfff0a189777965

**Comment by dimus** [comment]
@ruud-altenburg I showed @yroskov this ticket
