### ISSUE TITLE
output of a small file seems not CSV but a binary file?

### ISSUE THREAD

**Issue by wouteraddink** [GlobalNamesArchitecture/gnlist-resolver-gui#38]
see input and result files attached

**Comment by wouteraddink** [comment]
[match very small.txt](https://github.com/GlobalNamesArchitecture/gnlist-resolver-gui/files/1148626/match.very.small.txt)
[very small.txt](https://github.com/GlobalNamesArchitecture/gnlist-resolver-gui/files/1148625/very.small.txt)

**Comment by dimus** [comment]
After investigating this I found that the actual problem was not caused by the size of the file but by its extension. If an extension of a file was anything but ".csv" this problem would appear. Now any extension is possible and would create correct downloadable versions.
